### ISSUE TITLE
Fix the Date string 

### ISSUE THREAD

**Issue by ryan-broguiere** [ryan-broguiere/To-Do-App#4]
Currently the date returned is displayed in UTC, with some unnecessary info

It would be nice if it read `mm/dd/yyyy` `xx:xx:xx`  or just something a little bit cleaner. 

You can find the date variable in `task.js`

**Comment by pas-trop-de-zele** [comment]
Hi @ryan-broguiere, can I work on this issue?

**Comment by ryan-broguiere** [comment]
> Hi @ryan-broguiere, can I work on this issue?

sure
